### ISSUE TITLE
Update Composer Link

### ISSUE THREAD

**Issue by yvickers-rci** [dchesterton/marketo-rest-api#10]
Recently tried implementing this library using the recommended composer installation.  When I attempted to use the associateLead function, it caused an exception.  It looks like the composer source does have the latest edits and is pulling an older version of the library.

**Comment by dchesterton** [comment]
I've just tagged a new release which has the latest fixes. If you run `composer update` it should pull the new version.

**Comment by yvickers-rci** [comment]
That worked.  To anyone else with the issue, make sure to update the version you want in the composer.json file before running composer update so it will pull the new files.
