### ISSUE TITLE
Invalid Content Type

### ISSUE THREAD

**Issue by timkelty** [dchesterton/marketo-rest-api#14]
I'm trying to use the `addLeadsToList` method, but keep getting the following response:

```
array (size=2)
  'code' => string '612' (length=3)
  'message' => string 'Invalid Content Type' (length=20)
```

Is it because it needs to the post the body as with an `application/json` header?
http://developers.marketo.com/documentation/rest/add-leads-to-list/
http://stackoverflow.com/questions/28181325/why-invalid-content-type

**Comment by dchesterton** [comment]
Hi Tim, yes it seems Marketo have enforced the header recently. I tagged a release today which fixes the issue so if you run `composer update` it should be fixed.
