### ISSUE TITLE
The package is not available in a stable-enough version 

### ISSUE THREAD

**Issue by goyal-deepak1986** [dchesterton/marketo-rest-api#19]
whenever i run the below command 

composer require dchesterton/marketo-rest-api

than found the error " - The package is not available in a stable-enough version according to your minimum-stability setting" please tell me what i do just download your setup and after run the command 
![marketo_error](https://cloud.githubusercontent.com/assets/859632/7344329/38c29b8a-ece8-11e4-9b77-6c625cdee556.png)

Thanks

**Comment by dchesterton** [comment]
Please take a look at Composer's minimum-stability option: https://getcomposer.org/doc/04-schema.md#minimum-stability.
