### ISSUE TITLE
Guzzle 5+

### ISSUE THREAD

**Issue by respinoza** [dchesterton/marketo-rest-api#20]
Hello

I noticed this library uses Guzzle 3 (End of life), probably because of the PHP 5.3 requirements.
Is there any plan to bump it to at least Guzzle 5 (still maintained, requires PHP 5.4) ?

Maybe creating a new version to bump the requirements to 5.4 and Guzzle 5 would be nice.

I can contribute this but want to make sure if this will be helpful or the plan is to lock the library on PHP 5.3

Thank you

**Comment by slbmeh** [comment]
Fortunately Guzzle 3 and Guzzle 5 can live side by side.  I'm willing to contribute to a Guzzle 5 migration as well, but in my opinion PHP 5.3 should be supported until Ubuntu 12.04 hits end of life.

**Comment by respinoza** [comment]
Thank you for the reply, the reason makes sense but also the projects are moving forward and waiting for the EOL on Ubuntu is waiting until April 2017.
Also one thing to consider is that with the PSR-7, people will start to move to projects that support it as it enables all the middleware to be used on different frameworks (Symfony, Zend, etc.).

If the author wants, probably start a new branch/tag for the Guzzle 5 but before that, I would say put some effort into testing to make sure we are not breaking anything.

**Comment by nurikabe** [comment]
+1

Might make sense to have a "Version 1" tag for Guzzle 5 / PHP 5.4+ while maintaining support for PHP 5.3 in the alpha versions.

**Comment by dchesterton** [comment]
It's only targeting PHP 5.3 as the original server I was deploying to when I created the library was stuck on it.

I'm happy to create v1 with PHP 5.5/Guzzle 6 support. Symfony's targeting PHP 5.5 for it's next major version and Guzzle 6 has PSR-7 support so it seems to make sense. We can keep the 0.* version for back compatibility.

I don't have a Marketo installation to work with so if anyone's willing to contribute, that'd be appreciated.

**Comment by dchesterton** [comment]
I'm closing this for now. I'm no longer working with Marketo so I don't have an instance to test against. Pull requests are welcome if anyone has time to work on this.
